spring:
  application:
    name: user-center
  datasource: # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.184.212:13306/userCenter
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8080