spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: friend-sys
  datasource: # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ryan.mysql.address}/${ryan.mysql.database}?useUnicode=true&characterEncoding=utf8
    username: ${ryan.mysql.username}
    password: ${ryan.mysql.password}
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: ${server.port}
logging:
  level:
    root: info
